branches:
  only:
    - master

services:
  - docker

script:
  - make build || exit 1

after_success:
  - >
    [ "${TRAVIS_BRANCH}" == "master" ] &&
      (make release DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS)
